version: 2.1
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#go-golang
      - image: circleci/golang:1.13

    environment:
      TEST_DIR: /tmp/test-results

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}

      - run:
          name: Check
          command: make check

      - run:
        name: Build
        command: make build

      - run:
          name: Test
          command: make test

      - save_cache:
        key: go-mod-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
