version: 2.1
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#go-golang
      - image: circleci/golang:1.13

    environment:
      TEST_DIR: /tmp/test-results

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}

      - run:
          name: Check
          command: make deps check

      - run:
          name: Build
          command: make build

      - run:
          name: Test
          command: make testci

      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}
          paths:
            - "/go/pkg/mod"
            - "/go/bin"

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
